FROM yukimochi/container-caddy:edge

ADD assets.tar.gz /webroot
ADD public/maintain.html /webroot/public

ENTRYPOINT [ "/usr/bin/caddy" ]
CMD [ "--conf", "/etc/caddy/Caddyfile", "--log", "stdout", "--root", "/var/tmp" ]
