FROM caddy:2.6.0

WORKDIR /usr/share/caddy
EXPOSE 80 443

RUN rm -rf /usr/share/caddy/*
COPY public/ /usr/share/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
